name: CI

on: [push, pull_request]

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby-truffleruby
      min_version: 2.7

  test:
    needs: ruby-versions
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        exclude:
          - { os: windows-latest, ruby: truffleruby }
          - { os: windows-latest, ruby: truffleruby-head }
        include:
          - { os: windows-latest, ruby: ucrt }
          - { os: windows-latest, ruby: mswin }

    steps:
      - name: repo checkout
        uses: actions/checkout@v4

      - name: load ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # `bundle install` and cache

      # See https://github.com/oneclick/rubyinstaller2/issues/60
      # The builtin DLLs are preferred over the mingw64/vcpkg DLLs. This is a
      # temporary workaround until they update the DLLs to OpenSSL 3.5.x.
      - name: Update RI2/mswin builtin DLLs
        run: |
          if ("${{ matrix.ruby }}" -eq "mswin") {
            Copy-Item C:\vcpkg\installed\x64-windows\bin\libcrypto-3-x64.dll D:\ruby-mswin\bin\ruby_builtin_dlls
            Copy-Item C:\vcpkg\installed\x64-windows\bin\libssl-3-x64.dll D:\ruby-mswin\bin\ruby_builtin_dlls
          } else {
            Copy-Item C:\mingw64\bin\libcrypto-3-x64.dll C:\hostedtoolcache\windows\Ruby\*\x64\bin\ruby_builtin_dlls
            Copy-Item C:\mingw64\bin\libssl-3-x64.dll C:\hostedtoolcache\windows\Ruby\*\x64\bin\ruby_builtin_dlls
          }
        if: ${{ matrix.os == 'windows-latest' && (matrix.ruby == '3.2' || matrix.ruby == '3.3' || matrix.ruby == 'mswin') }}

      # Enable the verbose option in mkmf.rb to print the compiling commands.
      - name: enable mkmf verbose
        run:  echo "MAKEFLAGS=V=1" >> $GITHUB_ENV
        if: runner.os == 'Linux' || runner.os == 'macOS'

      - name: set flags to check compiler warnings
        run:  echo "RUBY_OPENSSL_EXTCFLAGS=-Werror" >> $GITHUB_ENV
        if: ${{ !matrix.skip-warnings }}

      - name: rake compile
        run:  bundle exec rake compile

      - name: rake test
        run:  bundle exec rake test TESTOPTS="-v --no-show-detail-immediately"
        timeout-minutes: 5

